version: "3.7"
services:
    redis:
        image: redis
        volumes:
            - ./redis_server/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
            - "6379:6379"
    master:
        build:
            context: ./master
            dockerfile: Dockerfile
        image: master_image
        container_name: master_container
        restart: always
        volumes:
          - "./LocalStorage/master:/app/LocalStorage"
        depends_on:
          - redis
        ports:
          - "10050:10050"

#    worker_summary:
#        build:
#            context: ./worker_summary
#            dockerfile: Dockerfile
#        image: worker_summary_image
#        restart: always
#        environment:
#            - task_name=gpt_summary
#        volumes:
#            - "./LocalStorage/worker:/app/LocalStorage"
#        depends_on:
#            - redis
    worker_word_summary:
        build:
            context: ./worker_core_sent
            dockerfile: Dockerfile
        image: worker_core_sent_image
        restart: always
        volumes:
            - "./LocalStorage/worker:/app/LocalStorage"
        depends_on:
            - redis